TARGETS_EXERCISE_BASE:=excercise_2_1 excercise_2_2
TARGETS_EXERCISE_SOLUTIONS:=2.1.mxm_static_scattering_col_alloc 2.1.mxm_static_scattering_row_alloc

TARGETS_EXERCISE:=$(TARGETS_EXERCISE_BASE) $(TARGETS_EXERCISE_SOLUTIONS)

EXERCISES_SRC_DIR:=$(dir $(realpath $(lastword $(MAKEFILE_LIST))))
EXERCISES_OBJ_DIR:=$(strip $(OBJ_DIR))/exercises

.PHONY: $(TARGETS_EXERCISE_BASE)
$(TARGETS_EXERCISE_BASE): %: $(BIN_DIR)/%

.INTERMEDIATE: $(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISE_BASE))

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_EXERCISE_BASE)): $(BIN_DIR)/%: $(EXERCISES_OBJ_DIR)/%.o $(LIB_DIR)/libmultiply.a $(LIB_DIR)/libarray.a | $(BIN_DIR)
	$(MPICC) $(LDFLAGS) $^ $(LIB_ARRAY_LINK_PUBLIC) $(LIB_MULTIPLY_LINK_PUBLIC) -o $@

$(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISE_BASE)): $(EXERCISES_OBJ_DIR)/%.o: $(EXERCISES_SRC_DIR)/%.c $(LIB_MULTIPLY_HEADERS_PUBLIC) $(LIB_ARRAY_HEADERS_PUBLIC) | $(EXERCISES_OBJ_DIR)
	$(MPICC) -c $(CFLAGS) -I$(INCLUDE_DIR) $< -o $@

.PHONY: $(TARGETS_EXERCISE_SOLUTIONS)
$(TARGETS_EXERCISE_SOLUTIONS): %: $(BIN_DIR)/%

.INTERMEDIATE: $(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISE_SOLUTIONS))

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_EXERCISE_SOLUTIONS)): $(BIN_DIR)/%: $(EXERCISES_OBJ_DIR)/%.o $(LIB_DIR)/libmultiply.a $(LIB_DIR)/libarray.a | $(BIN_DIR)
	$(MPICC) $(LDFLAGS) $^ $(LIB_ARRAY_LINK_PUBLIC) $(LIB_MULTIPLY_LINK_PUBLIC) -o $@

$(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISE_SOLUTIONS)): $(EXERCISES_OBJ_DIR)/%.o: $(EXERCISES_SRC_DIR)/solutions/%.c $(LIB_MULTIPLY_HEADERS_PUBLIC) $(LIB_ARRAY_HEADERS_PUBLIC) | $(EXERCISES_OBJ_DIR)
	$(MPICC) -c $(CFLAGS) -I$(INCLUDE_DIR) $< -o $@
